require:
  - 'rubocop-rspec'

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Style/Documentation:
  Include:
    - "lib/**/*"

Style/HashSyntax:
  EnforcedStyle: 'hash_rockets'

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Style/SignalException:
  EnforcedStyle: 'only_raise'

Metrics/ClassLength:
  Enabled: false

# FIXME: this seems to be broken, maybe it will be fixed later:
RSpec/FilePath:
  Enabled: false
