inherit_from: '.rubocop_todo.yml'

AllCops:
  DisplayCopNames: true

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Style/HashSyntax:
  EnforcedStyle: 'hash_rockets'

Metrics/ClassLength:
  Enabled: false
