AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Style/Documentation:
  Include:
    - "lib/**/*"

Style/HashSyntax:
  EnforcedStyle: 'hash_rockets'

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Style/SignalException:
  EnforcedStyle: 'only_raise'

Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - spec/**/*.rb
