sudo: false
cache: bundler
language: ruby
rvm:
  - 2.3.0
before_install: 'gem install bundler -v 1.11.2'
install: 'bundle install --without development'
script:
  - bundle exec rspec
after_success:
  - bundle exec codeclimate-test-reporter
